fullName: futs
service:
  type: ClusterIP
  ports:
    http: 8080
istio:
  useDelegationService: "false"
  virtualService:
    gateways: {}
    http:
      match:
        - uri:
            prefix: /fhir-ui-data-model-translation
      rewrite:
        uri: /
      retries:
        enable: true
        attempts: 3
        perTryTimeout: 1s
        retryOn: null
      timeout: null
    hosts: {}
  subsets:
    main:
      version: 1.0.0
      weight: "100"
      fhirProfile: fhir-profile-snapshots
      fhirProfileVersion: 4.0.0-b67
# activate Traffic mirroring, also called shadowing with the following lines
#      mirror:
#        version: 1.1.0
#        mirrorPercentage: 0
