{{- if and (hasKey .Values.istio "virtualService") (hasKey .Values.istio.virtualService "gateways") (gt (len .Values.istio.virtualService.gateways) 0) }}
{{- $name := .Values.fullName }}
{{- $namespace := .Release.Namespace }}
{{- $url := printf "%s.%s.svc.cluster.local" $name .Release.Namespace }}

apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: "{{ $name }}-virtual-service-external"
spec:
  {{- with .Values.istio.virtualService.gateways }}
  gateways:
    {{- toYaml . | nindent 4 }}
  {{- end}}
  {{- with .Values.istio.virtualService.hosts }}
  hosts:
    {{- toYaml . | nindent 4 }}
  {{- end}}
  http:
  {{- if .Values.istio.virtualService.externalHttp -}}
  {{- range .Values.istio.virtualService.externalHttp }}
    - match:
        {{- toYaml .match | nindent 6 }}
      delegate:
        name: "{{ .delegate.name }}-virtual-service"
        namespace: {{ $namespace }}
    {{- end }}
  {{- else -}}
  {{- range .Values.istio.virtualService.http }}
    - match:
        {{- toYaml .match | nindent 6 }}
      delegate:
        name: "{{ .delegate.name }}-virtual-service"
        namespace: {{ $namespace }}
    {{- end }}
  {{- end }}
{{- end }}